sudo: false
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file_glob: true
  file: nifi-prometheus-nar/target/*.nar
  skip_cleanup: true
  on:
    tags: true