version: '3.1'

volumes:
    grafana-data:

services:
    prometheus:
        image: prom/prometheus
        ports:
        - "9090:9090"
        volumes:
        - "./conf/prometheus.yml:/etc/prometheus/prometheus.yml"

    pushgateway:
        image: prom/pushgateway
        ports:
        - "9091:9091"

    nifi:
        build: .
        ports:
        - "8080:8080"

    grafana:
        image: grafana/grafana:latest
        ports:
        - "3000:3000"
        volumes:
        - "grafana-data:/var/lib/grafana"